# Generated by Django 2.0.6 on 2018-08-01 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=30, unique=True)),
                ('ContactPerson', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30, unique=True)),
                ('Address', models.TextField(blank=True, max_length=30)),
                ('PhoneNumber', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('State', models.CharField(blank=True, max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Zip', models.CharField(blank=True, max_length=30)),
                ('IsActive', models.CharField(blank=True, max_length=30)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailId', models.EmailField(max_length=30, unique=True)),
                ('PasswordEncrypted', models.CharField(max_length=30)),
                ('IsActive', models.BooleanField(default=False)),
                ('IsStaff', models.BooleanField(default=False)),
                ('IsAdmin', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('LastLogin', models.DateTimeField()),
                ('AccountId', models.CharField(max_length=10)),
            ],
        ),
    ]
