# Generated by Django 2.0.6 on 2018-12-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181128_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='AccountId',
            field=models.IntegerField(),
        ),
    ]
