# Generated by Django 2.0.6 on 2019-04-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181207_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='EmailId',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='PasswordEncrypted',
            field=models.CharField(max_length=50),
        ),
    ]
