# Generated by Django 2.1.4 on 2019-01-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptNumber', models.CharField(default='', max_length=30)),
                ('DeptName', models.CharField(default='', max_length=200)),
                ('SubDeptNumber', models.CharField(default='', max_length=30)),
                ('SubDeptName', models.CharField(default='', max_length=200)),
                ('CategoryNumber', models.CharField(default='', max_length=30)),
                ('CategoryName', models.CharField(default='', max_length=200)),
                ('UserId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('CompetitorsLogo', models.URLField(max_length=250)),
                ('ProductName', models.CharField(default='', max_length=250)),
                ('Description', models.CharField(default='', max_length=1000)),
                ('Rating', models.CharField(default='', max_length=250)),
                ('Image', models.URLField(max_length=250)),
                ('Price', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IGTIN', models.CharField(default='', max_length=30)),
                ('ICategoryNumber', models.CharField(default='', max_length=30)),
                ('IDescription', models.CharField(default='', max_length=200)),
                ('ISellSize', models.CharField(default='', max_length=30)),
                ('ISellUnitOfMeasure', models.CharField(default='', max_length=30)),
                ('IBrand', models.CharField(default='', max_length=30)),
                ('IStatus', models.CharField(default='', max_length=30)),
                ('UserId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('CompetitorFeatured', models.BooleanField(default=True)),
                ('WhatIfFeatured', models.BooleanField(default=True)),
                ('ExpiryDate', models.DateTimeField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('Price', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Date', models.DateTimeField()),
                ('UnitSales', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('UPC', models.CharField(default='', max_length=30)),
                ('StoreId', models.CharField(default='', max_length=30)),
                ('ProductPrice', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Cost', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('DeptNumber', models.CharField(default='', max_length=30)),
                ('SubDeptNumber', models.CharField(default='', max_length=30)),
                ('CategoryNumber', models.CharField(default='', max_length=30)),
                ('DeptName', models.CharField(default='', max_length=30)),
                ('SubDeptName', models.CharField(default='', max_length=30)),
                ('CategoryName', models.CharField(default='', max_length=30)),
                ('Quantity', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Peod', models.FloatField(blank=True, default=None, null=True)),
                ('UserId', models.IntegerField()),
                ('DateScraped', models.DateTimeField(blank=True, null=True)),
                ('FirstCompetitor', models.CharField(blank=True, default='', max_length=50)),
                ('FirstCompPrice', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('SecondCompetitor', models.CharField(blank=True, default='', max_length=50)),
                ('SecondCompPrice', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ThirdCompetitor', models.CharField(blank=True, default='', max_length=50)),
                ('ThirdCompPrice', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekNumber', models.IntegerField()),
                ('Year', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Date', models.DateTimeField()),
                ('Quantity', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ProductId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('EndingNumber', models.IntegerField()),
                ('MinCompPrice', models.IntegerField()),
                ('MaxCompPrice', models.IntegerField()),
                ('MinPriceChangeLimits', models.IntegerField()),
                ('MaxPriceChangeLimits', models.IntegerField()),
                ('MinMargin', models.IntegerField()),
                ('MaxMargin', models.IntegerField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreID', models.CharField(default='', max_length=30)),
                ('StoreName', models.CharField(default='', max_length=30)),
                ('StoreAddress1', models.CharField(default='', max_length=200)),
                ('StoreAddress2', models.CharField(default='', max_length=200)),
                ('StoreCity', models.CharField(default='', max_length=30)),
                ('StoreState', models.CharField(default='', max_length=30)),
                ('StoreZipCode', models.CharField(default='', max_length=30)),
                ('StorePhoneNumber', models.CharField(default='', max_length=30)),
                ('StoreStatus', models.CharField(default='', max_length=30)),
                ('StoreStatusDate', models.CharField(default='', max_length=30)),
                ('StoreTimeZone', models.CharField(default='', max_length=30)),
                ('StoreLatitude', models.CharField(default='', max_length=30)),
                ('StoreLongitude', models.CharField(default='', max_length=30)),
                ('UserId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcessDate', models.CharField(default='', max_length=30)),
                ('TillNumber', models.CharField(default='', max_length=30)),
                ('TransactionId', models.CharField(default='', max_length=200)),
                ('LineNumber', models.CharField(default='', max_length=200)),
                ('EmployeeId', models.CharField(default='', max_length=30)),
                ('StoreId', models.CharField(default='', max_length=30)),
                ('UPC', models.CharField(default='', max_length=30)),
                ('TransactionType', models.CharField(default='', max_length=30)),
                ('TransactionSubType', models.CharField(default='', max_length=30)),
                ('DepartmentId', models.CharField(default='', max_length=30)),
                ('Quantity', models.CharField(default='', max_length=30)),
                ('ProductPrice', models.CharField(default='', max_length=30)),
                ('TotalAmount', models.CharField(default='', max_length=30)),
                ('Cost', models.CharField(default='', max_length=30)),
                ('PriceTypeId', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
