# Generated by Django 2.0.6 on 2019-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='MaxVolumeChangeLimits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='MinVolumeChangeLimits',
            field=models.IntegerField(null=True),
        ),
    ]
