# Generated by Django 2.0.6 on 2019-01-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190118_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='Description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.URLField(default='imgno.png', max_length=250),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='licence',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stores',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
    ]
