# Generated by Django 2.0.6 on 2019-01-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190121_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('PromotionType', models.CharField(default='', max_length=250)),
                ('PromotionName', models.CharField(default='', max_length=250)),
                ('PromotionSpend', models.CharField(default='', max_length=250)),
                ('SalesWithoutPromo', models.CharField(default='', max_length=30)),
                ('SalesWithPromo', models.CharField(default='', max_length=30)),
                ('BICLocation', models.CharField(default='', max_length=250)),
                ('BICType', models.CharField(default='', max_length=250)),
                ('TotalOpportunity', models.CharField(default='', max_length=30)),
                ('SalesLift', models.CharField(default='', max_length=30)),
                ('UserId', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='producthistory',
            name='PriceTypeId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='PromoId',
            field=models.IntegerField(default=0),
        ),
    ]
