# Generated by Django 2.0.6 on 2019-04-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190129_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('WeekNumber', models.IntegerField()),
                ('SeasonalityIndex', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('UserId', models.IntegerField()),
                ('DateCreated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='CoefficientDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='InterceptCoefficient',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='PriceCoefficient',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='PromoIndexCoefficient',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='WeekCoefficient',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='promotions',
            name='PromotionIndex',
            field=models.IntegerField(null=True),
        ),
    ]
