# Generated by Django 2.0.6 on 2019-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_seasonality_baselinesales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorTierRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PeodRange', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('CompetitorTier', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ImpactPercentValue', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='CompetitorIndex',
            field=models.IntegerField(null=True),
        ),
    ]
