# Generated by Django 2.0.6 on 2019-04-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20190414_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ProductUrl',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
