# Generated by Django 2.0.6 on 2019-05-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_details_producturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='NB1_PriceCoefficient',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='NB1_ProductId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='NB1_PromoCoefficient',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
