# Generated by Django 2.0.6 on 2019-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_auto_20190513_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('Stores', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('AuthStores', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('DisplayPresentPercent', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('AuthDisplayPercent', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('SalesLift', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('DisplayPercent', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Sales', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Location', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('Division', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Region', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Stores', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('DisplayPresent', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('SalesLift', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('DisplayPercent', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Sales', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
