# Generated by Django 2.0.6 on 2019-05-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_display_location_region_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('SalesLift', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Execution', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('BestInClassDisplay', models.CharField(default='', max_length=250)),
                ('AdditionalSales', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('MissingDollars', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
    ]
