# Generated by Django 2.0.6 on 2019-05-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_valuecapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Brand',
            field=models.CharField(default='', max_length=30),
        ),
    ]
